### ISSUE TITLE
Fixing pnts points move points

### ISSUE THREAD

**Issue by deex2** [minoue/CheckTools#4]
Hi,

Setting the value of pnts to 0 here:
https://github.com/minoue/CheckTools/blob/master/meshChecker/src/meshChecker.cpp#L194
move points.
Is it what we want? Or do we want to "freeze" them?

Only solution I found to freeze them is to do this:
`cmds.polyMoveVertex(name, constructionHistory=False)`
I didn't find anything with the C++ API.

**Comment by minoue** [comment]
It seems like rigging wants pnts to be frozen. I don't what actual issues but maybe something related to deformers..
Anyway, it moves points and that's fine.
cmds.polyMoveVertex() freezes pnts values in most of time like 99% but not 100%. Sometimes, in some mesh which has very small values such as 1e-09 in pnts, polyMoveVertex doesn't freeze to 0. 
So we usually do double fix, cmds.polyMoveVetex, then resetPnts. Even if the first command doesn't fix pnts, the second one set back to 0. In such case, moving points is no problem as pnts values are so small and we never see differences in shape.

But again, polyMoveVertex fix it in most of time and I don't know if this issues happens in other companies : (

**Comment by deex2** [comment]
Yes I have seen this "bug" of "small values".
To fix this I do:

```
vtx_name = '{}.vtx[0]'.format(name)

topology_mod_attr = "{}.allowTopologyMod".format(name)
if not cmds.getAttr(topology_mod_attr):
    cmds.setAttr(topology_mod_attr, lock=False)
    cmds.setAttr(topology_mod_attr, True)

# ugly tricks: set a vertex with a value to fix the maya precision bug
cmds.move(0, 1, 0, vtx_name, r=True, os=True, wd=True)
cmds.polyMoveVertex(name, constructionHistory=False)
cmds.move(0, -1, 0, vtx_name, r=True, os=True, wd=True)
cmds.polyMoveVertex(name, constructionHistory=False)
```
Moving the first vertex and moving it back fix it. But I guess setting them to 0 after the first polyMoveVertex is a faster solution.
Do you know if there is a way to do a polyMoveVertex with the C++ API?
polyMoveVertex with heavy meshes is slow.

**Comment by minoue** [comment]
Ahh, thank you, now I found out when this happens and when doesn't by reading your way to fix it.


>  _Do you know if there is a way to do a polyMoveVertex with the C++ API?_

That's what I was looking for... but can't find a good way so far. I know using polyMoveVertex on heavy mesh is such a headache. 

Please let me know if you find a better way to fix this.

**Comment by minoue** [comment]
Closed
