### ISSUE TITLE
OpenMP dependency

### ISSUE THREAD

**Issue by bareya** [minoue/CheckTools#8]
I was told that OpenMP is not being uses, but it's required by the CMake configuration. 

We would have to review all OpenMP's dependency.

**Comment by bareya** [comment]
this is only one dependency I have found:

https://github.com/minoue/CheckTools/blob/master/uvOverlapChecker/src/findUvOverlaps.cpp#L192

I believe this dependency is broken, since there are no OpenMP includes in the source file nor anywhere else in the project?

**Comment by minoue** [comment]
I think OpenMP doesn't need any includes for maya plugins.
I tested using a model with 2-3000 objects, and the for loop below that line get roughly 2.5 times faster so looks like it's working.
I haven't used TBB yet so I'll keep this omp at the moment.
Thanks for flagging.
